<?php

/**
 * @file
 * Module hooks for govdelivery_bulletins module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_twig_theme().
 */
function govdelivery_bulletins_twig_theme($existing, $type, $theme, $path) {
  $bulletin_variables = [
    'body' => '',
    'click_tracking' => FALSE,
    'header' => '',
    'from_address' => '',
    'open_tracking' => FALSE,
    'publish_rss' => FALSE,
    'send_time' => '',
    'subject' => '',
    'footer' => '',
    'sms_body' => '',
    'urgent' => FALSE,
    'share_content_enabled' => FALSE,
    'categories' => [],
    'topics' => [],
  ];

  return [
    'govdelivery_bulletin_xml' => [
      'variables' => $bulletin_variables,
    ],
    'govdelivey_bulletin_test_xml' => [
      'variables' => ['email_addresses' => []],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function govdelivery_bulletins_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.govdelivery_bulletins':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
